Importing Numpy Library

In [ ]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
A.shape

(2, 2)

In [ ]:
B.shape

(2, 2)

Adding two Matrices

In [ ]:
sum = A + B

In [ ]:
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [ ]:
print(matrix_1)

[[2 7 9]
 [6 0 2]
 [8 3 1]]


In [ ]:
print(matrix_2)

[[18 17 11]
 [ 6 15  2]
 [ 9  8 11]]


In [ ]:
sum = np.add(matrix_1, matrix_2)

In [ ]:
print(sum)

[[20 24 20]
 [12 15  4]
 [17 11 12]]


In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [ ]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: ignored

We get this error because shape of matrix_3 and matrix_4 are different

**Matrix Subtraction**

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
difference = A - B

In [ ]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [ ]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [ ]:
print(matrix_1)

[[0 7 9]
 [6 9 9]
 [7 9 2]]


In [ ]:
print(matrix_2)

[[ 7  8 16]
 [ 0  9  8]
 [16 17 12]]


In [ ]:
diff = np.subtract(matrix_1, matrix_2)

In [ ]:
print(diff)

[[ -7  -1  -7]
 [  6   0   1]
 [ -9  -8 -10]]


**Multiplying a matrix by a scalar**

In [ ]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[0 4 6 7]
 [5 4 6 8]
 [4 3 8 0]
 [8 2 7 8]]


In [ ]:
product = np.multiply(x,y)

In [ ]:
print(product)

[[ 0 20 30 35]
 [25 20 30 40]
 [20 15 40  0]
 [40 10 35 40]]


**Multiplying 2 Matrices**

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [ ]:
print(matrix_3)

[[4 2 2]
 [1 2 3]
 [0 1 4]]


In [ ]:
print(matrix_4)

[[3 1 1 3]
 [2 2 0 3]
 [1 2 3 2]]


In [ ]:
product = np.dot(matrix_3, matrix_4)

In [ ]:
print(product)

[[18 12 10 22]
 [10 11 10 15]
 [ 6 10 12 11]]


In [ ]:
product.shape

(3, 4)

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [ ]:
product = np.dot(matrix_3, matrix_4)

ValueError: ignored

**Element wise Matrix Multiplication**

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [ ]:
print(matrix_3)

[[1 3 1]
 [2 3 3]
 [3 0 2]]


In [ ]:
print(matrix_4)

[[1 0 2]
 [2 2 4]
 [0 0 4]]


In [ ]:
product = np.multiply(matrix_3, matrix_4)

In [ ]:
print(product)

[[ 1  0  2]
 [ 4  6 12]
 [ 0  0  8]]


In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [ ]:
product = np.multiply(matrix_3, matrix_4)

ValueError: ignored